[package]
name = "rust_study"
version = "0.1.0"
authors = ["yangyang <ofyang@qq.com>"]
edition = "2018"

[dependencies]
#for http request
reqwest = "0.9.19"

#for web server
iron = "*"
router = "0.6.0"
actix-web = "1.0.5"

#json lib
serde_json = "1.0.40"
serde = "*"
