[package]
name = "study_iron"
version = "0.1.0"
authors = ["yangyang <ofyang@qq.com>"]
edition = "2018"
#指明所在工作空间的根路径
workspace = "../../.."

[dependencies]
#for web server
router = "0.6.0"
iron = "0.6.1"
#json lib
serde_json = "1.0.40"
serde = "1.0.99"