[package]
name = "t10_3_0_csv_challenge"
version = "0.1.0"
authors = ["yangyang <ofyang@qq.com>"]
edition = "2018"
workspace = "../../../../../.."

[dependencies]
# 依赖库：Parse command line argument by defining a struct.
structopt = "0.3.16"
structopt-derive = "0.4.9"